resources:
  - url: /customcards/custom-lovelace/card-tools.js
    type: js
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css
    
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.min.js
    type: module
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
    type: module

  - url: /customcards/custom-lovelace/camera-card.js
    type: module

  - url: /customcards/custom-lovelace/alarm_control_panel-card.js
    type: js
  - url: /customcards/custom-lovelace/atomic-calendar.js
    type: module
  - url: /customcards/custom-lovelace/auto-entities.js
    type: js
  - url: /customcards/custom-lovelace/bignumber-card.js
    type: js
  - url: /customcards/custom-lovelace/browser-commander.js?v.1
    type: js
  - url: /customcards/custom-lovelace/button-card.js
    type: module
  - url: /customcards/custom-lovelace/card-modder.js
    type: js
  - url: /customcards/custom-lovelace/compact-custom-header/compact-custom-header.js?v.1
    type: module
  - url: /customcards/custom-lovelace/dummy-entity-row.js
    type: js
  - url: /customcards/custom-lovelace/entity-attributes-card.js
    type: js
  - url: /customcards/custom-lovelace/fold-entity-row.js
    type: js
  - url: /customcards/custom-lovelace/gap-card.js
    type: js
  - url: /customcards/custom-lovelace/krisinfo-card.js
    type: js
  - url: /customcards/custom-lovelace/layout-card.js
    type: js
  - url: /customcards/custom-lovelace/mini-graph-card-bundle.js?v1
    type: module
  - url: /customcards/custom-lovelace/mini-media-player-bundle.js
    type: module
  # - url: /customcards/custom-lovelace/plan-coordinates.js
  #   type: js
  - url: /customcards/custom-lovelace/pollenkoll-card.js
    type: js
  - url: /customcards/custom-lovelace/popup-card.js
    type: js
  - url: /customcards/custom-lovelace/secondaryinfo-entity-row.js
    type: js
  - url: /customcards/custom-lovelace/simple-weather-card.bundle.js?v=0.1.0
    type: module
  - url: /customcards/custom-lovelace/slider-entity-row.js
    type: js
  # - url: /customcards/custom-lovelace/slideshow-card.js
  #   type: js 
  - url: /customcards/custom-lovelace/state-attribute-element.js
    type: js
  # - url: /customcards/custom-lovelace/state-element.js
  #   type: js
  - url: /customcards/custom-lovelace/state-switch.js
    type: js
  - url: /customcards/custom-lovelace/surveillance-card.js
    type: module
  - url: /customcards/custom-lovelace/text-element.js
    type: js
  - url: /customcards/custom-lovelace/toggle-lock-entity-row.js
    type: js
  - url: /customcards/custom-lovelace/tracker-card.js
    type: js
  - url: /customcards/custom-lovelace/upcoming-media-card.js
    type: js
  - url: /customcards/custom-lovelace/useful-markdown-card.js
    type: js
  # - url: /customcards/custom-lovelace/username-element.js
  #   type: js
  - url: /customcards/custom-lovelace/vertical-stack-in-card.js
    type: js
  
  - url: /customcards/custom-lovelace/live-camera-card.js?v.0.0.3
    type: module



title: Home
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_home_info_view.yaml
  - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_system_info_view.yaml
  - !include lovelace/31_system_graphs.yaml
  - !include lovelace/40_camera_view.yaml
  # - !include lovelace/50_cat_view.yaml
  - !include lovelace/60_traffic_view.yaml
  - !include lovelace/60_floorplan_view.yaml
  # - !include lovelace/70_isa_view.yaml
  - !include lovelace/80_automations_view.yaml
  - !include lovelace/101_dashboard.yaml
  # - !include lovelace/minimal_dash.yaml  
  # - !include lovelace/103_dashboard_test.yaml
  - !include lovelace/krisinfotest.yaml
  # - !include lovelace/everything.yaml
  - !include lovelace/areas.yaml

  - !include lovelace/99_settings_view.yaml
  - !include lovelace/102_tiny_dashboard_1.yaml
  
  
  
  
  