sensor:
  - platform: krisinformation
    name: 'Krisinformation Stockholm 1km'
    radius: 1
  - platform: krisinformation
    name: 'Krisinformation Stockholm'
    county: 'Stockholms län'
    radius: 50
  - platform: krisinformation
    name: 'Krisinformation All'
    radius: 7000
    
  - platform: krisinformation
    country: 'Sverige'
    
automation:
  - alias: '[Security] Krisinformation Alert'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.krisinformation_all
      to: "Alert"
    action:
      - service: notify.discord_krisinfo_hook
        data_template:
          message: >
            ALERT! {{states.sensor.krisinformation_all.attributes.messages[0].Headline}} - {{states.sensor.krisinformation_all.attributes.messages[0].Message}} {{states.sensor.krisinformation_all.attributes.messages[0].Web}}

  - alias: '[Security] Krisinformation News'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.krisinformation_all
      to: "News"
    action:
      - service: notify.discord_krisinfo_hook
        data_template:
          message: >
            {{states.sensor.krisinformation_all.attributes.messages[0].Headline}} - {{states.sensor.krisinformation_all.attributes.messages[0].Message}} {{states.sensor.krisinformation_all.attributes.messages[0].Web}}