# homeassistant:
#   customize_glob:
#     sensor.pollen*:
#       custom_ui_state_card: state-card-custom-ui
#       templates:
#         hs_color: "if (state === '0') return [0, 0];
#         else if (state === '1') return [50, 70];
#         else if (state === '2') return [40, 70];
#         else if (state === '3') return [30, 70];
#         else if (state === '4') return [20, 85];
#         else if (state === '5') return [10, 65];
#         else if (state === '6') return [0, 85];"
    
sensor:      
  - platform: pollenniva
    scan_interval: 4
    sensors:
      - city: Stockholm
        days_to_track: 3
        allergens:
          - Björk
          - Gråbo
          - Gräs
          - Ambrosia
          - Al
          - Alm
          - Ek
          - Hassel
          - Sälg / Vide
  - platform: pollenniva
    scan_interval: 4
    sensors:
      - city: Gävle
        days_to_track: 3
        allergens:
          - Björk
          - Gråbo
          - Gräs
          - Ambrosia
          - Al
          - Alm
          - Ek
          - Hassel
          - Sälg / Vide

  # - platform: template
  #   sensors:
  #     pollen_grabo:
  #       friendly_name: "Pollen: gråbo"
  #       entity_id: "sensor.pollenkoll_stockholm"
  #       value_template: >-
  #         {% if is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'i.h.') -%}
  #           no levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'L') -%}
  #           low levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'L-M') -%}
  #           low-moderate levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'M') -%}
  #           moderate levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'M-H') -%}
  #           moderate-high levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'H') -%}
  #           high levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'H-H+') -%}
  #           very high levels
  #         {%- endif %}
  #     pollen_gras:
  #       friendly_name: "Pollen: gräs"
  #       entity_id: "sensor.pollenkoll_stockholm"
  #       value_template: >-
  #         {% if is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'i.h.') -%}
  #           no levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'L') -%}
  #           low levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'L-M') -%}
  #           low-moderate levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'M') -%}
  #           moderate levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'M-H') -%}
  #           moderate-high levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'H') -%}
  #           high levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'H-H+') -%}
  #           very high levels
  #         {%- endif %}
  #     pollen_bjork:
  #       friendly_name: "Pollen: björk"
  #       entity_id: "sensor.pollenkoll_stockholm"
  #       value_template: >-
  #         {% if is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'i.h.') -%}
  #           no levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'L') -%}
  #           low levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'L-M') -%}
  #           low-moderate levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'M') -%}
  #           moderate levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'M-H') -%}
  #           moderate-high levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'H') -%}
  #           high levels
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'H-H+') -%}
  #           very high levels
  #         {%- endif %}
  #     pollen_levels:
  #       friendly_name: "Pollen levels"
  #       entity_id: "sensor.pollenkoll_stockholm"
  #       value_template: >-
  #         {%- if is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'M') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'M-H') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'H') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'H-H+') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'M') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'M-H') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'H') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'H-H+') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'M') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'M-H') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'H') -%}
  #           high
  #         {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'H-H+') -%}
  #           high
  #         {%- else %}
  #           low
  #         {%- endif %}