input_boolean:
  cat_food:
    name: Order Cat Food
    icon: mdi:barcode-scan
  cat_litter:
    name: Order Cat Litter
    icon: mdi:emoticon-poop

  cut_claws_ziggy:
    name: Cut Claws Ziggy
    icon: mdi:cat
  cut_claws_honey:
    name: Cut Claws Honey
    icon: mdi:cat
  cut_fur_ziggy:
    name: Cut Fur Ziggy
    icon: mdi:cat
  cut_fur_honey:
    name: Cut Fur Honey
    icon: mdi:cat

input_number:
  cat_feeder_stepper_control:
    name: Cat Feeder Stepper Control
    initial: 0
    min: -1000
    max: 1000
    step: 1
    mode: slider

automation:
  - alias: Write Stepper Value to ESP
    trigger:
      platform: state
      entity_id: input_number.cat_feeder_stepper_control
    action:
      - service: esphome.cat_feeder_control_stepper
        data_template:
          target: '{{ trigger.to_state.state | int }}'