# homeassistant:
#   customize:
#     input_boolean.cleaning_day:
#       confirm_controls_show_lock: true

input_boolean:
  cleaning_day:
    name: Cleaning Day
    icon: mdi:broom


automation:
  # - alias: Cleaning Day On
  #   initial_state: 'on'  
  #   trigger: 
  #     - platform: state
  #       entity_id: calendar.cleaning_day
  #       to: 'on'
  #   action:
  #     - service: input_boolean.turn_on
  #       entity_id: input_boolean.cleaning_day

  # - alias: Cleaning Day Off
  #   initial_state: 'on'
  #   trigger: 
  #     - platform: state
  #       entity_id: calendar.cleaning_day
  #       to: 'off'
  #   action:
  #     - service: input_boolean.turn_off
  #       entity_id: input_boolean.cleaning_day

  - alias: Cleaning Mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.unlocked_by
        to: 'Cleaners'
    condition:
    - condition: state
      entity_id: input_boolean.cleaning_day
      state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: automation.ring_doorbell_motion_lights
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.home_alarm
      - service: script.turn_on
        entity_id: script.cleaning_time
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: 'Cleaning time'
          message: 'Cleaners have arrived'

  - alias: Cleaning Mode Off
    initial_state: 'on'
    trigger:
      - platform: time
        minutes: '/15'
        seconds: 00
    condition:
      - condition: time
        after: '13:00:00'
      - condition: state
        entity_id: binary_sensor.passage_pir_sensor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.upstairs_hallway_pir_sensor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d000165ff1f
        state: 'off'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d0001a66256
        state: 'off'
      - condition: state
        entity_id: input_boolean.cleaning_day
        state: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: automation.ring_doorbell_motion_lights
      - service: script.turn_on
        entity_id: script.cleaning_time_over
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm
      - service: homeassistant.turn_off
        entity_id: input_boolean.cleaning_day