homeassistant:
  customize:
    input_boolean.guest_mode:
      templates:
        icon: >
          if (state === 'on') return 'mdi:account-group';
          else if (state === 'off') return 'mdi:account-multiple-minus';
        icon_color: >
          if (state === 'on') return 'rgb(56, 150, 56)';
          else if (state === 'off') return 'rgb(249, 251, 255)';

  customize_glob:
    input_boolean.guest_mode:
      templates:
        hs_color: "if (state === 'off') return [0, 0];
        else return [116, 85];"

input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:account-group



automation:
- alias: '[House] Guest Mode On By Presence'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.naprapajsvenzon, device_tracker.marek, device_tracker.anette, device_tracker.mareksiphonex, device_tracker.00d9d1f2c9c7 #emelie
      to: home
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.guest_mode
    - service: notify.ios_isabellas_iphone_x
      data_template:
        title: 'You have a guest!'
        message: >
          '{{ trigger.to_state.name }} is here'

- alias: '[House] Guest Mode On'
  initial_state: 'on'
  trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'on'
  action:
    - service: automation.turn_off
      entity_id: automation.ring_doorbell_motion_lights
    - service: notify.ios_isabellas_iphone_x
      data_template:
        title: 'Guest mode on'
        message: >
          'Some automations turned off'

- alias: '[House] Guest Mode Off'
  initial_state: 'on'
  trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: 'off'
  action:
    - service: automation.turn_on
      entity_id: automation.ring_doorbell_motion_lights
    - service: notify.ios_isabellas_iphone_x
      data_template:
        title: 'Guest mode off'
        message: >
          'Automations turned on again'