homeassistant:
  customize:
    input_select.washing_machine_status:
      icon: mdi:washing-machine
    sensor.washer:
      icon: mdi:washing-machine

input_select:  
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Clean

sensor:
  - platform: template
    sensors:
      washer:
        friendly_name: Washer Idle
        value_template: "{{ states('sensor.washer_plug_power') | int < 3.4 }}"


group:
  laundry_card:
    name: Laundry
    entities:
      - input_select.washing_machine_status
      - input_select.dryer_status
      - sensor.washer
      - sensor.dryer
      - switch.laundry_line_drying
      - history_graph.dryer_graph

## ------------------------------------------------------------------- ##
automation:
  - alias: Laundry Washing Machine Start
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.washer
      from: 'True'
      to: 'False'
    # condition:
    #   condition: or
    #   conditions:
    #     - condition: state
    #       entity_id: sensor.washing_machine_status
    #       state: Idle
        # - condition: state
        #   entity_id: sensor.washing_machine_status
        #   state: Clean
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Running

  - alias: Laundry Washing Machine Clean After Timeout
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.washer
      from: 'False'
      to: 'True'
      for:
        minutes: 5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Clean


  - alias: Laundry Washing Machine Emptied
    trigger:
      - platform: state
        entity_id: binary_sensor.washer_hatch
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Idle
      - service: light.turn_on
        data:
          entity_id: light.floorlamp_uplight
          rgb_color: 
            - 255
            - 214
            - 170
      - service: light.turn_off
        entity_id: light.floorlamp_uplight



## ------------------------  NOTIFICATIONS ------------------------  ##

  - alias: Laundry Notification On Washing Machine Done
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_status
        to: Clean
        for:
          minutes: 1
      - platform: state
        entity_id: device_tracker.isabella
        to: 'Home'
      # - platform: state
      #   entity_id: device_tracker.stefan
      #   to: 'Home'
      #   for:
      #     minutes: 10
      - platform: time
        at: '08:01:00'
    condition:
      condition: and
      conditions:
        - condition: time
          before: '23:00:00'
          after: '08:00:00'
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
        - condition: template
          value_template: >
            {% if states.automation.laundry_notification_on_washing_machine_done.last_triggered is not none %}
              {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.laundry_notification_on_washing_machine_done.attributes.last_triggered) | int > 1800 %} true {% else %} false
              {% endif %}
            {% else %}
            false
            {% endif %}
    action:
      - service: light.turn_on
        data:
          entity_id: light.floorlamp_uplight
          brightness: 150
          color_name: 'red'

      - service: notify.ios_isabellas_iphone_x
      ## Hubby has back pain and is relieved of this duty temporarely
      # - service_template: >
      #     {% if (is_state('device_tracker.isabella', 'home')) and (is_state('device_tracker.stefan', 'home'))  %}
      #       notify.all
      #     {% elif is_state('device_tracker.isabella', 'home') %}
      #       notify.ios_isabellas_iphone_x
      #     {% elif is_state('device_tracker.stefan', 'home') %}
      #       notify.ios_stefan_iphone_7
      #     {% endif %}
        data:
          message: 'Take care of it now?'
          title: 'Washing machine is done!'
          data:
            push:
              badge: 0
              category: "washer"

  - alias: Laundry Washing Machine Emptied
    initial_state: 'on'
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHER_EMPTIED
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Idle
      - service: light.turn_on
        data:
          entity_id: light.floorlamp_uplight
          rgb_color: 
            - 255
            - 214
            - 170
      - delay: 00:00:20
      - service: light.turn_off
        entity_id: light.floorlamp_uplight
      - service: notify.ios_isabellas_iphone_x
        data:
          message: 'The laundry is taken care of'

  - alias: Laundry Washing Machine Snoozed
    initial_state: 'on'
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: WASHER_NOT_EMPTIED
    action:
      - delay: 0:30
      - service: notify.ios_isabellas_iphone_x
      # - service_template: >
      #     {% if (is_state('device_tracker.isabella', 'home')) and (is_state('device_tracker.stefan', 'home'))  %}
      #       notify.all
      #     {% elif is_state('device_tracker.isabella', 'home') %}
      #       notify.ios_isabellas_iphone_x
      #     {% elif is_state('device_tracker.stefan', 'home') %}
      #       notify.ios_stefan_iphone_7
      #     {% endif %}
        data:
          message: 'Take care of it now?'
          title: 'Washing machine is done!'
          data:
            push:
              badge: 0
              category: "washer"

  - alias: 'Notification on high humidity in downstairs bathroom'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.humidity_158d0001a2a899
        above: 43
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.isa_status_dropdown
          state: 'Home'
        - condition: time
          after: '09:00:00'
          before: '23:00:00'
        # - condition: template
        #   value_template: >
        #     {% if states.automation.notification_on_high_humidity_in_downstairs_bathroom.last_triggered is not none %}
        #       {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.notification_on_high_humidity_in_downstairs_bathroom.attributes.last_triggered) | int > 1800 %} true {% else %} false
        #       {% endif %}
        #     {% else %}
        #     false
        #     {% endif %}
    action:
    - service: notify.ios_isabellas_iphone_x
      data:
        title: 'High humidity in downstairs bathroom'
        message: 'Turn on the fan'