homeassistant:
  customize:
    sensor.small_chili_temperature:
      icon: mdi:thermometer
    sensor.big_chili_temperature:
      icon: mdi:thermometer
    sensor.herbs_temperature:
      icon: mdi:thermometer   
    sensor.small_chili_moisture:
      icon: mdi:water-percent
    sensor.big_chili_moisture:
      icon: mdi:water-percent
    sensor.herbs_moisture:
      icon: mdi:water-percent     
    sensor.herbs_light_intensity:
      icon: mdi:theme-light-dark
    sensor.small_chili_light_intensity:
      icon: mdi:theme-light-dark

      

group:
  plant_card:
    view: no
    name: Plants
    entities:
      - plant.herbs
      - plant.small_chili
      - plant.big_chili

sensor:
  - platform: min_max
    name: Greenhouse temperature
    type: mean
    entity_ids:
      - sensor.small_chili_temperature
      - sensor.big_chili_temperature
      - sensor.herbs_temperature

  # - platform: miflora
  #   mac: "C4:7C:8D:60:A5:B3"
  #   name: Small chili
  #   median: 3
  #   cache: 10800
  #   force_update: false
  #   monitored_conditions:
  #     - temperature
  #     - light
  #     - moisture
  #     - conductivity
  #     - battery

  # - platform: miflora
  #   mac: "C4:7C:8D:63:13:9B"
  #   name: Herbs
  #   median: 3
  #   cache: 10800
  #   force_update: false
  #   monitored_conditions:
  #     - temperature
  #     - light
  #     - moisture
  #     - conductivity
  #     - battery

  # - platform: miflora
  #   mac: "C4:7C:8D:65:C3:A6"
  #   name: Big chili
  #   median: 3
  #   cache: 10800
  #   force_update: false
  #   monitored_conditions:
  #     - temperature
  #     - light
  #     - moisture
  #     - conductivity
  #     - battery

  - platform: mqtt
    state_topic: "homeassistant/sensor/herbs_temperature/state"
    name: Herbs temperature
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "homeassistant/sensor/big_chili_temperature/state"
    name: Big chili temperature
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "homeassistant/sensor/small_chili_temperature/state"
    name: Small chili temperature
    unit_of_measurement: '°C'

  - platform: mqtt
    state_topic: "homeassistant/sensor/herbs_moisture/state"
    name: Herbs moisture
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "homeassistant/sensor/big_chili_moisture/state"
    name: Big chili moisture
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "homeassistant/sensor/small_chili_moisture/state"
    name: Small chili moisture
    unit_of_measurement: '%'

  - platform: mqtt
    state_topic: "homeassistant/sensor/herbs_battery/state"
    name: herbs battery
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "homeassistant/sensor/big_chili_battery/state"
    name: Big chili battery
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "homeassistant/sensor/small_chili_battery/state"
    name: Small chili battery
    unit_of_measurement: '%'

plant:
  herbs:
    sensors:
      moisture: sensor.herbs_moisture
      battery: sensor.herbs_battery
      temperature: sensor.herbs_temperature
      # conductivity: sensor.herbs_conductivity
      # brightness: sensor.herbs_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 10
    # min_conductivity: 500
    # max_conductivity: 3000

  small_chili:
    sensors:
      moisture: sensor.small_chili_moisture
      battery: sensor.small_chili_battery
      temperature: sensor.small_chili_temperature
      # conductivity: sensor.small_chili_conductivity
      # brightness: sensor.small_chili_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 10
    # min_conductivity: 500
    # max_conductivity: 3000 

  big_chili:
    sensors:
      moisture: sensor.big_chili_moisture
      battery: sensor.big_chili_battery
      temperature: sensor.big_chili_temperature
      # conductivity: sensor.big_chili_conductivity
      # brightness: sensor.big_chili_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 10
    # min_conductivity: 500
    # max_conductivity: 3000      