homeassistant:
  customize:
    binary_sensor.motion_sensor_158d000165ff1f:
      friendly_name: Living Room Motion
    binary_sensor.motion_sensor_158d0001a66256:
      friendly_name: Hallway Motion
    sensor.passage_pir_luminance:
      friendly_name: Passage Lux
      icon: mdi:theme-light-dark
    sensor.upstairs_hallway_pir_luminance:
      friendly_name: Upstairs Hallway Lux
      icon: mdi:theme-light-dark
    switch.roomba:
      icon: mdi:robot-vacuum

sensor:
  - platform: template
    sensors:
      passage_movement:
        friendly_name: 'Passage Movement'
        entity_id: "binary_sensor.passage_pir_sensor"
        value_template: '{% if is_state("binary_sensor.passage_pir_sensor", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.passage_pir_sensor", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'

      upstairs_hallway_movement:
        friendly_name: 'Upstairs Hallway Movement'
        entity_id: "binary_sensor.upstairs_hallway_pir_sensor"
        value_template: '{% if is_state("binary_sensor.upstairs_hallway_pir_sensor", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.upstairs_hallway_pir_sensor", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'    

      # living_room_movement:
      #   friendly_name: 'Living Room Motion'
      #   entity_id: "binary_sensor.motion_sensor_158d000165ff1f"
      #   value_template: '{% if is_state("binary_sensor.motion_sensor_158d000165ff1f", "on") %}Movement detected{% else %}No movement{% endif %}'
      #   icon_template: '{% if is_state("binary_sensor.motion_sensor_158d000165ff1f", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'

      # hallway_movement:
      #   friendly_name: 'Hallway Movement'
      #   entity_id: "binary_sensor.motion_sensor_158d0001a66256"
      #   value_template: '{% if is_state("binary_sensor.motion_sensor_158d0001a66256", "on") %}Movement detected{% else %}No movement{% endif %}'
      #   icon_template: '{% if is_state("binary_sensor.motion_sensor_158d0001a66256", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'