homeassistant:
  customize:
    sensor.system_magic_mirror_rpi:
      icon: mdi:raspberrypi
    sensor.system_hass_rpi:
      icon: mdi:home-assistant      
    sensor.system_stefan_computer:
      icon: mdi:monitor
    sensor.system_isa_laptop:
      icon: mdi:laptop-windows
    sensor.system_isa_computer:
      icon: mdi:monitor
    sensor.system_asus_router:
      icon: mdi:wifi
    sensor.system_netgear_router:
      icon: mdi:wifi
    sensor.system_printer:
      icon: mdi:printer
    sensor.system_nas:
      icon: mdi:server
    sensor.system_chromecast_bedroom:
      icon: mdi:cast
    sensor.system_shield:
      icon: mdi:android
    # sensor.system_shield_2:
    #   icon: mdi:android
    sensor.system_ipad:
      icon: mdi:tablet-ipad
    sensor.system_movie_system:
      icon: mdi:speaker
    sensor.system_samsung65:
      icon: mdi:television
    # sensor.system_hue_hub:
      # icon: mdi:lightbulb-outline
    sensor.system_ikea_gateway:
      icon: mdi:google-keep
    sensor.system_xiaomi_gateway:
      icon: mdi:circle-outline
    sensor.system_ip_camera:
      icon: mdi:webcam
    sensor.system_galaxy_tab:
      icon: mdi:tablet-android
    sensor.system_samsung49:
      icon: mdi:television
    sensor.system_ir_blaster:
      icon: mdi:remote
    sensor.system_ir_blaster_bedroom:
      icon: mdi:remote
    sensor.system_ir_blaster_living_room:
      icon: mdi:remote
    sensor.system_withings_scale:
      icon: mdi:scale-bathroom
    sensor.system_sonos_3:
      icon: mdi:speaker
    sensor.system_milight_hub:
      icon: mdi:google-keep
    sensor.system_ring_doorbell:
      icon: mdi:doorbell-video
    sensor.system_ring_chime_pro:
      icon: mdi:wifi
    sensor.system_ring_chime:
      icon: mdi:bell-outline
    sensor.system_isa_dell_xps:
      icon: mdi:laptop-windows
    sensor.system_stefan_laptop:
      icon: mdi:laptop-windows

  customize_glob:
    sensor.system_*:
      custom_ui_state_card: state-card-custom-ui
      templates:
        hs_color: "if (state === 'Online') return [0, 0];
        else if (state === 'Unknown') return [40, 70];
        else if (state === 'Offline') return [0, 85];"    
      
sensor:
  - platform: template
    sensors:
        system_milight_hub:
          friendly_name: 'Milight Hub'
          value_template: "{{ 'Online' if is_state('device_tracker.milight_controller', 'home') else 'Offline' }}"
        system_nas:
          friendly_name: 'Synology NAS'
          value_template: "{{ 'Online' if is_state('device_tracker.synology_nas', 'home') else 'Offline' }}"
        system_samsung65:
          friendly_name: 'Living Room TV'
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_tv', 'home') else 'Offline' }}"
        system_samsung49:
          friendly_name: 'Bedroom TV'
          value_template: "{{ 'Online' if is_state('device_tracker.bedroom_tv', 'home') else 'Offline' }}"
        system_movie_system:
          friendly_name: 'Living Room Movie System'
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_movie_system', 'home') else 'Offline' }}"
        system_netgear_router:
          friendly_name: 'Netgear Router'
          value_template: "{{ 'Online' if is_state('device_tracker.netgear_router', 'home') else 'Offline' }}"
        system_shield:
          friendly_name: 'NVidia Shield'
          value_template: "{{ 'Online' if is_state('device_tracker.nvidia_shield', 'home') else 'Offline' }}"
        # system_shield_2:
        #   friendly_name: 'NVidia Shield 2'
        #   value_template: "{{ 'Online' if is_state('device_tracker.shield', 'home') else 'Offline' }}"
        system_chromecast_bedroom:
          friendly_name: 'Chromecast Bedroom'
          value_template: "{{ 'Online' if is_state('device_tracker.chromecast_bedroom', 'home') else 'Offline' }}"
        system_stefan_computer:
          friendly_name: 'Stefan computer'
          value_template: "{{ 'Online' if is_state('device_tracker.stefan_computer', 'home') else 'Offline' }}"
        system_stefan_laptop:
          friendly_name: 'Stefan laptop'
          value_template: "{{ 'Online' if is_state('device_tracker.cnstefang', 'home') else 'Offline' }}"
        system_isa_computer:
          friendly_name: 'Isas computer'
          value_template: "{{ 'Online' if is_state('device_tracker.isa_computer', 'home') else 'Offline' }}"
        system_isa_laptop:
          friendly_name: 'Isas old laptop'
          value_template: "{{ 'Online' if is_state('device_tracker.isa_laptop', 'home') else 'Offline' }}"
        system_isa_dell_xps:
          friendly_name: 'Isa Dell XPS'
          value_template: "{{ 'Online' if is_state('device_tracker.desktop39i618g', 'home') else 'Offline' }}"        
        system_printer:
          friendly_name: 'HP Printer'
          value_template: "{{ 'Online' if is_state('device_tracker.hp_printer', 'home') else 'Offline' }}"
        system_ipad:
          friendly_name: 'iPad'
          value_template: "{{ 'Online' if is_state('device_tracker.paddan', 'home') else 'Offline' }}"
        system_galaxy_tab:
          friendly_name: 'Galaxy Tab'
          value_template: "{{ 'Online' if is_state('device_tracker.android8c0fc07d9694a5a2', 'home') else 'Offline' }}"
        # system_hue_hub:
        #   friendly_name: 'Philips Hue Gateway'
        #   value_template: "{{ 'Online' if is_state('device_tracker.philipshue', 'home') else 'Offline' }}"
        system_asus_router:
          friendly_name: 'Asus Router'
          value_template: "{{ 'Online' if is_state('device_tracker.router_asus', 'home') else 'Offline' }}"
        system_ip_camera:
          friendly_name: 'IP Camera'
          value_template: "{{ 'Online' if is_state('device_tracker.sannce_ip_camera', 'home') else 'Offline' }}"
        system_ir_blaster:
          friendly_name: 'Broadlink IR Blaster Hallway'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_hallway', 'home') else 'Offline' }}"
        system_withings_scale:
          friendly_name: 'Withings scale'
          value_template: "{{ 'Online' if is_state('device_tracker.0024e40a2868', 'home') else 'Offline' }}"
        system_ir_blaster_bedroom:
          friendly_name: 'Broadlink IR Blaster Bedroom'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_bedroom', 'home') else 'Offline' }}"
        system_ir_blaster_living_room:
          friendly_name: 'Broadlink IR Blaster Living Room'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_rmminiccec6f', 'home') else 'Offline' }}"
        # system_ikea_gateway:
        #   friendly_name: 'Ikea Trådfri Gateway'
        #   value_template: "{{ 'Online' if is_state('device_tracker.tradfri_gateway', 'home') else 'Offline' }}"
        system_xiaomi_gateway:
          friendly_name: 'Xiaomi Gateway'
          value_template: "{{ 'Online' if is_state('device_tracker.xiaomi_gateway', 'home') else 'Offline' }}"
        system_sonos:
          friendly_name: 'Sonos'
          value_template: "{{ 'Online' if is_state('device_tracker.sonos_play_3', 'home') else 'Offline' }}"
        system_magic_mirror_rpi:
          friendly_name: 'Rpi Downstairs'
          value_template: "{{ 'Online' if is_state('device_tracker.magic_mirror_rpi', 'home') else 'Offline' }}"
        system_hass_rpi:
          friendly_name: 'Rpi Upstairs'
          value_template: "{{ 'Online' if is_state('device_tracker.raspberrypi', 'home') else 'Offline' }}"
        system_ring_doorbell:
          friendly_name: 'Ring'
          value_template: "{{ 'Online' if is_state('device_tracker.ring', 'home') else 'Offline' }}"
        system_ring_chime_pro:
          friendly_name: 'Ring Chime Pro'
          value_template: "{{ 'Online' if is_state('device_tracker.ring_chime_pro', 'home') else 'Offline' }}"
        system_ring_chime:
          friendly_name: 'Ring Chime Pro'
          value_template: "{{ 'Online' if is_state('device_tracker.ring_chime', 'home') else 'Offline' }}"
        system_dafang:
          friendly_name: 'Rpi Upstairs'
          value_template: "{{ 'Online' if is_state('device_tracker.7811dc70faaf', 'home') else 'Offline' }}"

# group:
#   system_info_view:
#     name: System info
#     icon: mdi:lan
#     view: yes
#     entities:
#       - device_tracker.isabella
#       - device_tracker.stefan
#       - group.device_states
#       - group.computer_states
#       - group.media_states
#       - group.hass_card
#       - group.internet_card
#       - group.system_monitor_card
#       - history_graph.internet_speed_tests
#       - group.isabella
#       - group.stefan
#       - group.ring_front_door
#       - group.appdaemon_automations

#   appdaemon_automations:
#     name: Appdaemon Apps
#     entities:
#       - input_boolean.ad_presence


#   device_states:
#     name: Device status
#     entities:
#     - sensor.system_printer
#     - sensor.system_nas
#     - sensor.system_ipad
#     - sensor.system_galaxy_tab
#     - sensor.system_ip_camera
#     - sensor.system_ir_blaster
#     - sensor.system_ir_blaster_bedroom
#     - sensor.system_ir_blaster_living_room
#     - sensor.system_withings_scale
#     # - sensor.system_hue_hub
#     - sensor.system_milight_hub
#     - sensor.system_ikea_gateway
#     - sensor.system_xiaomi_gateway
#     - sensor.system_hass_rpi
#     - sensor.system_magic_mirror_rpi
#     - sensor.system_ring_doorbell
#     - sensor.system_ring_chime_pro
#     - sensor.system_ring_chime

#   computer_states:
#     name: Computer status
#     entities:
#     - sensor.system_stefan_computer
#     - sensor.system_isa_computer
#     - sensor.system_isa_laptop

#   media_states:
#     name: Media player status
#     entities:
#     - sensor.system_samsung65
#     - sensor.system_samsung49
#     - sensor.system_movie_system
#     - sensor.system_chromecast_bedroom
#     - sensor.system_shield
#     - sensor.system_shield_2
#     - sensor.system_sonos

automation:
  - alias: 'Device Status'
    initial_state: 'on'
    trigger:
         - platform: state
           entity_id:
              - sensor.system_asus_router
              - sensor.system_netgear_router
              - sensor.system_printer
              - sensor.system_nas
              # - sensor.system_hue_hub
              - sensor.system_ir_blaster
              - sensor.system_ir_blaster_bedroom
              - sensor.system_ip_camera
            #  - sensor.system_ir_blaster_living_room
              - sensor.system_xiaomi_gateway
              - sensor.system_milight_hub
              - sensor.system_ring_doorbell
              - sensor.system_ring_chime_pro
              - sensor.system_ring_chime
           to: 'offline'
           for:
             minutes: 5
    action:
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: 'Device {{ trigger.to_state.name }} is'
          message: >
            '{{ trigger.to_state.state }}'